name: deact_router
description: An client-side router for deact
version: 0.1.0
homepage: https://github.com/exaby73/deact_router

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  deact: ^1.0.0

dev_dependencies:
  lint: ^1.7.2
  lints: ^1.0.0
